### ISSUE TITLE
`BplusTools [9c855568]` not registered

### ISSUE THREAD

**Issue by sorumehta** [heyx3/Bplus.jl#127]
Hey, great job on creating this helpful library and documentation! I am new to Julia and this package looks really useful.
However, on running `instantiate`, I get this error: ERROR: expected package `BplusTools [9c855568]` to be registered

**Comment by heyx3** [comment]
Hi! It's currently un-registered because it's made of 3 smaller packages, and one of those smaller packages is not yet registered. It will be registered after I finish adding some new features to the ECS.

However you can directly add the 2 registered sub-packages (BplusCore and BplusApp), then add the unregistered one (BplusTools) using the github URL, for example in the REPL do `] add http:/github.com/heyx3/BplusTools`.

**Comment by heyx3** [comment]
Going to leave this issue open until I actually release B+.

I've finished the work on BplusTools, so I just need to wait 3 days for it to be accepted into the package repo, then another 3 days for Bplus itself to be accepted into the package repo.

Then B+ will be released!
